#!/bin/bash

set -ex
if [ $(id -u) -ne 0 ]; then
	exec sudo $0
fi

BUILDIR=$(cd `dirname $0` && pwd -P)
TMPDIR=$(mktemp -d)

ARCH="x86_64"
VERSION="2019.01.01"

FAKEROOT="https://github.com/takezoh/ArchLinux-WSL/releases/download/1.0/fakeroot-tcp-1.23-1-${ARCH}.pkg.tar.xz"

cd $TMPDIR

curl -LO http://ftp.jaist.ac.jp/pub/Linux/ArchLinux/iso/${VERSION}/archlinux-bootstrap-${VERSION}-${ARCH}.tar.gz
tar xzf archlinux-bootstrap-${VERSION}-${ARCH}.tar.gz

mount --bind root.${ARCH} root.${ARCH}
cd root.${ARCH}

cp /etc/resolv.conf etc/
cp $BUILDIR/linux_files/pacman.conf etc/
cp $BUILDIR/linux_files/mirrorlist etc/pacman.d/
sed -i -e 's/#en_US.UTF-8/en_US.UTF-8/' etc/locale.gen
echo "LANG=en_US.UTF-8" > etc/locale.conf

sed -i -e 's/^SigLevel *$/SigLevel=Never/' etc/pacman.conf

(cd tmp && curl -LO $FAKEROOT)

mount -t proc /proc proc
mount --rbind /sys sys
mount --rbind /dev dev
mount --rbind /run run

chroot . pacman-key --init
chroot . pacman-key --populate archlinux
chroot . pacman -Syu --noconfirm
chroot . pacman -S --noconfirm sed
chroot . pacman -S --noconfirm base
chroot . pacman -S --noconfirm base-devel sudo
yes | chroot . pacman -U --force /tmp/`basename $FAKEROOT`
yes | chroot . pacman -Scc
chroot . locale-gen

umount -l .

rm -rf tmp/*
rm -rf var/cache/pacman/pkg/*

echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." > etc/resolv.conf
cp $BUILDIR/linux_files/pacman.conf etc/
sed -i -e "s/^# %wheel ALL=.*NOPASSWD:.*$/%wheel ALL=(ALL) NOPASSWD: ALL/" etc/sudoers

tar --ignore-failed-read -czf ../install.tar.gz *

cp ../install.tar.gz $BUILDIR
